/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SwingView;

import Controller.BookDAO;
import Controller.DBConnection;
import Model.Book;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author honahl
 */
public class ManageBook extends javax.swing.JFrame {

    private final Connection connection = DBConnection.getConnection();

    private DefaultTableModel model;

    private BookDAO bookDAO = new BookDAO();

    /**
     * Creates new form BookManager
     */
    public ManageBook() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTableAboutBook();

        addWindowListener(new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new HomePage().setVisible(true);
                    }
                });
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel8 = new javax.swing.JLabel();
        IdSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name_search = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        search_Button = new keeptoo.KGradientPanel();
        search_text = new javax.swing.JLabel();
        back_button = new javax.swing.JLabel();
        Id_Modify = new javax.swing.JTextField();
        name_Modify = new javax.swing.JTextField();
        type_Modify = new javax.swing.JTextField();
        field_modify = new javax.swing.JTextField();
        author_modify = new javax.swing.JTextField();
        year_modify = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Creat_button = new keeptoo.KGradientPanel();
        creat_text = new javax.swing.JLabel();
        delete_button = new keeptoo.KGradientPanel();
        delete_text = new javax.swing.JLabel();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rSTableMetro1 = new rojerusan.RSTableMetro();
        pulish_modify = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1170, 680));

        jLabel8.setFont(new java.awt.Font("Nimbus Sans L", 1, 23)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Manage Book");
        jLabel8.setToolTipText("");

        IdSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 102, 204)));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");

        name_search.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 51, 153)));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("name");

        search_Button.setkEndColor(new java.awt.Color(255, 255, 0));
        search_Button.setkStartColor(new java.awt.Color(255, 255, 0));
        search_Button.setPreferredSize(new java.awt.Dimension(214, 40));
        search_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_ButtonMouseClicked(evt);
            }
        });

        search_text.setFont(new java.awt.Font("Nimbus Sans L", 1, 18)); // NOI18N
        search_text.setForeground(new java.awt.Color(0, 0, 153));
        search_text.setText("SEARCH");
        search_text.setToolTipText("");
        search_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout search_ButtonLayout = new javax.swing.GroupLayout(search_Button);
        search_Button.setLayout(search_ButtonLayout);
        search_ButtonLayout.setHorizontalGroup(
            search_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_ButtonLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(search_text, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        search_ButtonLayout.setVerticalGroup(
            search_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_ButtonLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(search_text)
                .addGap(15, 15, 15))
        );

        back_button.setFont(new java.awt.Font("Nimbus Sans L", 1, 18)); // NOI18N
        back_button.setForeground(new java.awt.Color(255, 255, 255));
        back_button.setText("BACK TO HOME");
        back_button.setToolTipText("");
        back_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdSearch)
                    .addComponent(name_search)
                    .addComponent(search_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(back_button)
                .addGap(33, 33, 33))
        );

        Id_Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_ModifyActionPerformed(evt);
            }
        });

        jLabel3.setText("ID : ");

        jLabel1.setText("BookName :");

        jLabel5.setText("BookField : ");

        jLabel6.setText("BookType :");

        jLabel9.setText("BookAuthor  :");

        jLabel11.setText("year publising:");

        Creat_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Creat_buttonMouseClicked(evt);
            }
        });

        creat_text.setFont(new java.awt.Font("Nimbus Sans L", 1, 18)); // NOI18N
        creat_text.setForeground(new java.awt.Color(255, 255, 255));
        creat_text.setText("CREAT");
        creat_text.setToolTipText("");
        creat_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creat_textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Creat_buttonLayout = new javax.swing.GroupLayout(Creat_button);
        Creat_button.setLayout(Creat_buttonLayout);
        Creat_buttonLayout.setHorizontalGroup(
            Creat_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Creat_buttonLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(creat_text, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        Creat_buttonLayout.setVerticalGroup(
            Creat_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Creat_buttonLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(creat_text)
                .addContainerGap())
        );

        delete_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_buttonMouseClicked(evt);
            }
        });

        delete_text.setFont(new java.awt.Font("Nimbus Sans L", 1, 18)); // NOI18N
        delete_text.setForeground(new java.awt.Color(255, 255, 255));
        delete_text.setText("DELETE");
        delete_text.setToolTipText("");
        delete_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout delete_buttonLayout = new javax.swing.GroupLayout(delete_button);
        delete_button.setLayout(delete_buttonLayout);
        delete_buttonLayout.setHorizontalGroup(
            delete_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_buttonLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(delete_text, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        delete_buttonLayout.setVerticalGroup(
            delete_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, delete_buttonLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(delete_text)
                .addContainerGap())
        );

        kGradientPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kGradientPanel6MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Nimbus Sans L", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("UPDATE");
        jLabel16.setToolTipText("");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel6Layout = new javax.swing.GroupLayout(kGradientPanel6);
        kGradientPanel6.setLayout(kGradientPanel6Layout);
        kGradientPanel6Layout.setHorizontalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel6Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        kGradientPanel6Layout.setVerticalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BooKID", "Name", "Type", "Field", "Author", "Publish", "Publish year"
            }
        ));
        rSTableMetro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSTableMetro1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rSTableMetro1);

        jLabel10.setText("book publishing : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(type_Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(name_Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(Id_Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Creat_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(field_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(author_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73)
                                        .addComponent(kGradientPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(year_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pulish_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(67, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id_Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(author_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type_Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(pulish_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Creat_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kGradientPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_textMouseClicked
        if (IdSearch.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "id cant be empty");
        } else {
            searchBook();
        }

    }//GEN-LAST:event_search_textMouseClicked

    private void search_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_ButtonMouseClicked
        if (IdSearch.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "id cant be empty");
        } else {
            searchBook();
        }

    }//GEN-LAST:event_search_ButtonMouseClicked

    private void Id_ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_ModifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_ModifyActionPerformed

    private void creat_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creat_textMouseClicked
        creat();

    }//GEN-LAST:event_creat_textMouseClicked

    private void Creat_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Creat_buttonMouseClicked
        creat();
    }//GEN-LAST:event_Creat_buttonMouseClicked

    private void delete_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_textMouseClicked
        delete();
    }//GEN-LAST:event_delete_textMouseClicked

    private void delete_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_buttonMouseClicked
        delete();
    }//GEN-LAST:event_delete_buttonMouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        update();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void kGradientPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel6MouseClicked
        update();
    }//GEN-LAST:event_kGradientPanel6MouseClicked

    private void rSTableMetro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSTableMetro1MouseClicked
        int row = rSTableMetro1.getSelectedRow();
        TableModel getModel = rSTableMetro1.getModel();

        if (row >= 0) {
            Id_Modify.setText(getModel.getValueAt(row, 0).toString());
            name_Modify.setText(getModel.getValueAt(row, 1).toString());
            type_Modify.setText(getModel.getValueAt(row, 2).toString());
            field_modify.setText(getModel.getValueAt(row, 3).toString());
            author_modify.setText(getModel.getValueAt(row, 4).toString());
            pulish_modify.setText(getModel.getValueAt(row, 5).toString());
            year_modify.setText(getModel.getValueAt(row, 6).toString());
        }
    }//GEN-LAST:event_rSTableMetro1MouseClicked

    private void back_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_buttonMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_back_buttonMouseClicked

    /**
     * @param args the comand line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ManageBook().setVisible(true);
//            }
//        });
    }

    public void searchBook() {

        try {
            Book book = bookDAO.search(Integer.valueOf(IdSearch.getText()));
            if (book != null) {
                Id_Modify.setText(Integer.toString(book.getId()));
                name_Modify.setText(book.getName());
                type_Modify.setText(book.getType());
                field_modify.setText(book.getField());
                author_modify.setText(book.getAuthor());
                pulish_modify.setText(book.getPublish());
                year_modify.setText(Integer.toString(book.getYear()));
                deleteRow();
                Object[] obj = {book.getId(), book.getName(), book.getType(), book.getField(), book.getAuthor(), book.getPublish(), book.getYear()};
                model.addRow(obj);
            } else if (!name_search.getText().equals("")) {

                ResultSet rs = bookDAO.searchByName(name_search.getText());
                if (rs != null) {
                    deleteRow();
                    while (rs.next()) {
                        int id = rs.getInt(1);
                        String name = rs.getString(2);
                        String type = rs.getString(3);
                        String field = rs.getString(4);
                        String author = rs.getString(5);
                        String publish = rs.getString(6);
                        int year = rs.getInt(7);

                        Object[] obj = {id, name, type, field, author, publish, year};
                        model = (DefaultTableModel) rSTableMetro1.getModel();
                        model.addRow(obj);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "cant find this book");
                }

            } else {
                JOptionPane.showMessageDialog(this, "cant find this book");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "invalid text");
            e.printStackTrace();
        }

    }

    public void creat() {
        try {
            Book book = new Book();
            book.setName(name_Modify.getText());
            book.setType(type_Modify.getText());
            book.setField(field_modify.getText());
            book.setPublish(pulish_modify.getText());
            book.setAuthor(author_modify.getText());
            book.setYear(Integer.parseInt(year_modify.getText()));

            if (bookDAO.creat(book)) {
                deleteRow();
                JOptionPane.showMessageDialog(this, "add successfull");
                setTableAboutBook();
            } else {
                JOptionPane.showMessageDialog(this, "add nonsuccessfull");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "invalid text");
            e.printStackTrace();
        }

    }

    public void delete() {
        try {
            Book book = new Book();
            book.setId(Integer.parseInt(Id_Modify.getText()));
            book.setName(name_Modify.getText());
            book.setType(type_Modify.getText());
            book.setField(field_modify.getText());
            book.setPublish(pulish_modify.getText());
            book.setAuthor(author_modify.getText());
            book.setYear(Integer.parseInt(year_modify.getText()));

            if (bookDAO.delete(book)) {
                JOptionPane.showMessageDialog(this, "delete successfull");
                deleteRow();
                setTableAboutBook();
            } else {
                JOptionPane.showMessageDialog(this, "delete nonsuccessfull");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "invalid text");
            e.printStackTrace();
        }
    }

    public void update() {
        try {
            Book book = new Book();
            book.setId(Integer.parseInt(Id_Modify.getText()));
            book.setName(name_Modify.getText());
            book.setType(type_Modify.getText());
            book.setField(field_modify.getText());
            book.setPublish(pulish_modify.getText());
            book.setAuthor(author_modify.getText());
            book.setYear(Integer.parseInt(year_modify.getText()));

            if (bookDAO.update(book)) {
                deleteRow();
                JOptionPane.showMessageDialog(this, "update successfull");
                Object[] obj = {book.getId(), book.getName(), book.getType(), book.getField(), book.getAuthor(), book.getPublish(), book.getYear()};
                model = (DefaultTableModel) rSTableMetro1.getModel();
                model.addRow(obj);
            } else {
                JOptionPane.showMessageDialog(this, "update nonsuccessfull");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "invalid text");
            e.printStackTrace();
        }
    }

    public void deleteRow() {
        int n = model.getRowCount();
        for (int i = n - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }

    public void setTableAboutBook() {
        String sql = "SELECT * FROM BOOK";
        try {
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(sql);

            while (rs.next()) {
                int id = rs.getInt(1);
                String name = rs.getString(2);
                String type = rs.getString(3);
                String field = rs.getString(4);
                String author = rs.getString(5);
                String publish = rs.getString(6);
                int year = rs.getInt(7);

                Object[] obj = {id, name, type, field, author, publish, year};
                model = (DefaultTableModel) rSTableMetro1.getModel();
                model.addRow(obj);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel Creat_button;
    private javax.swing.JTextField IdSearch;
    private javax.swing.JTextField Id_Modify;
    private javax.swing.JTextField author_modify;
    private javax.swing.JLabel back_button;
    private javax.swing.JLabel creat_text;
    private keeptoo.KGradientPanel delete_button;
    private javax.swing.JLabel delete_text;
    private javax.swing.JTextField field_modify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel6;
    private javax.swing.JTextField name_Modify;
    private javax.swing.JTextField name_search;
    private javax.swing.JTextField pulish_modify;
    private rojerusan.RSTableMetro rSTableMetro1;
    private keeptoo.KGradientPanel search_Button;
    private javax.swing.JLabel search_text;
    private javax.swing.JTextField type_Modify;
    private javax.swing.JTextField year_modify;
    // End of variables declaration//GEN-END:variables
}
