/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SwingView;

import Controller.EmployeeDAO;
import Model.Employee;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author honahl
 */
public class ManageEmployee extends javax.swing.JFrame {

    private DefaultTableModel model;
    private EmployeeDAO employeeDAO = new EmployeeDAO();

    /**
     * Creates new form ManageEmployee
     */
    public ManageEmployee() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Num_emp.setText(Integer.toString(employeeDAO.CountNumberOfEmployee()));
        Num_singed.setText(Integer.toString(employeeDAO.CountNumberOfEmployeeSignedIn()));
        Num_logout.setText(Integer.toString(employeeDAO.CountNumberOfEmployeeLogOut()));
        setTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel8 = new javax.swing.JLabel();
        IdSearch = new javax.swing.JTextField();
        name_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        search_Button = new keeptoo.KGradientPanel();
        search_text = new javax.swing.JLabel();
        back_button = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rSTableMetro1 = new rojerusan.RSTableMetro();
        Id_Modify = new javax.swing.JTextField();
        name_Modify = new javax.swing.JTextField();
        address_Modify = new javax.swing.JTextField();
        phone_Modify1 = new javax.swing.JTextField();
        usr_Modify2 = new javax.swing.JTextField();
        year_Modify4 = new javax.swing.JTextField();
        gender_Modify5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel11 = new javax.swing.JLabel();
        Num_emp = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel12 = new javax.swing.JLabel();
        Num_singed = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel13 = new javax.swing.JLabel();
        Num_logout = new javax.swing.JLabel();
        add_button = new keeptoo.KGradientPanel();
        add_text = new javax.swing.JLabel();
        deleteBook_button = new keeptoo.KGradientPanel();
        deleteBook_text = new javax.swing.JLabel();
        update_button = new keeptoo.KGradientPanel();
        Update_text = new javax.swing.JLabel();
        signed_Modify6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1208, 780));

        jLabel8.setFont(new java.awt.Font("Nimbus Sans L", 1, 23)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Manage Employee");
        jLabel8.setToolTipText("");

        IdSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 102, 204)));

        name_search.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 51, 153)));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("name");

        search_Button.setkEndColor(new java.awt.Color(255, 255, 0));
        search_Button.setkStartColor(new java.awt.Color(255, 255, 0));
        search_Button.setPreferredSize(new java.awt.Dimension(214, 40));
        search_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_ButtonMouseClicked(evt);
            }
        });

        search_text.setFont(new java.awt.Font("Nimbus Sans L", 1, 18)); // NOI18N
        search_text.setForeground(new java.awt.Color(0, 0, 153));
        search_text.setText("SEARCH");
        search_text.setToolTipText("");
        search_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout search_ButtonLayout = new javax.swing.GroupLayout(search_Button);
        search_Button.setLayout(search_ButtonLayout);
        search_ButtonLayout.setHorizontalGroup(
            search_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_ButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_text, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        search_ButtonLayout.setVerticalGroup(
            search_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_ButtonLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(search_text)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        back_button.setFont(new java.awt.Font("Nimbus Sans L", 1, 18)); // NOI18N
        back_button.setForeground(new java.awt.Color(255, 255, 255));
        back_button.setText("BACK TO HOME");
        back_button.setToolTipText("");
        back_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdSearch)
                    .addComponent(name_search)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(search_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(back_button)
                .addGap(78, 78, 78))
        );

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "emp_id", "fullName", "Gender", "year", "address", "phone", "username", "IsSignIn"
            }
        ));
        rSTableMetro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSTableMetro1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rSTableMetro1);

        Id_Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_ModifyActionPerformed(evt);
            }
        });

        phone_Modify1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_Modify1ActionPerformed(evt);
            }
        });

        usr_Modify2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usr_Modify2ActionPerformed(evt);
            }
        });

        year_Modify4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year_Modify4ActionPerformed(evt);
            }
        });

        gender_Modify5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender_Modify5ActionPerformed(evt);
            }
        });

        jLabel1.setText("FullName :");

        jLabel3.setText("ID : ");

        jLabel5.setText("Gende :");

        jLabel6.setText("year :");

        jLabel7.setText("Address :");

        jLabel9.setText("Phone :");

        jLabel10.setText("username :");

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jLabel11.setText("Number of employee");

        Num_emp.setFont(new java.awt.Font("Nimbus Sans", 1, 36)); // NOI18N
        Num_emp.setText("10");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(Num_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Num_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jLabel12.setText("employee in working");

        Num_singed.setFont(new java.awt.Font("Nimbus Sans", 1, 36)); // NOI18N
        Num_singed.setText("10");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(Num_singed, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(4, 4, 4)
                .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Num_singed, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jLabel13.setText("employee not in working");

        Num_logout.setFont(new java.awt.Font("Nimbus Sans", 1, 36)); // NOI18N
        Num_logout.setText("10");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(Num_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(4, 4, 4)
                .addComponent(kGradientPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Num_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_buttonMouseClicked(evt);
            }
        });

        add_text.setFont(new java.awt.Font("Nimbus Sans L", 1, 12)); // NOI18N
        add_text.setForeground(new java.awt.Color(255, 255, 255));
        add_text.setText("CREATE");
        add_text.setToolTipText("");
        add_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout add_buttonLayout = new javax.swing.GroupLayout(add_button);
        add_button.setLayout(add_buttonLayout);
        add_buttonLayout.setHorizontalGroup(
            add_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_buttonLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(add_text)
                .addGap(55, 55, 55))
        );
        add_buttonLayout.setVerticalGroup(
            add_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_buttonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_text)
                .addGap(14, 14, 14))
        );

        deleteBook_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBook_buttonMouseClicked(evt);
            }
        });

        deleteBook_text.setFont(new java.awt.Font("Nimbus Sans L", 1, 12)); // NOI18N
        deleteBook_text.setForeground(new java.awt.Color(255, 255, 255));
        deleteBook_text.setText("DELETE ");
        deleteBook_text.setToolTipText("");
        deleteBook_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBook_textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout deleteBook_buttonLayout = new javax.swing.GroupLayout(deleteBook_button);
        deleteBook_button.setLayout(deleteBook_buttonLayout);
        deleteBook_buttonLayout.setHorizontalGroup(
            deleteBook_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteBook_buttonLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(deleteBook_text)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        deleteBook_buttonLayout.setVerticalGroup(
            deleteBook_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteBook_buttonLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(deleteBook_text)
                .addGap(15, 15, 15))
        );

        update_button.setPreferredSize(new java.awt.Dimension(157, 45));
        update_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_buttonMouseClicked(evt);
            }
        });

        Update_text.setFont(new java.awt.Font("Nimbus Sans L", 1, 12)); // NOI18N
        Update_text.setForeground(new java.awt.Color(255, 255, 255));
        Update_text.setText("UPDATE ");
        Update_text.setToolTipText("");
        Update_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update_textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout update_buttonLayout = new javax.swing.GroupLayout(update_button);
        update_button.setLayout(update_buttonLayout);
        update_buttonLayout.setHorizontalGroup(
            update_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_buttonLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(Update_text)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        update_buttonLayout.setVerticalGroup(
            update_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_buttonLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Update_text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        signed_Modify6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signed_Modify6ActionPerformed(evt);
            }
        });

        jLabel14.setText("signed :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(409, 409, 409)
                            .addComponent(deleteBook_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(address_Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(name_Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Id_Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(58, 58, 58)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phone_Modify1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(year_Modify4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(usr_Modify2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(65, 65, 65)
                                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel14))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(signed_Modify6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(gender_Modify5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id_Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_Modify1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usr_Modify2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addComponent(signed_Modify6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address_Modify, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year_Modify4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(gender_Modify5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBook_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_textMouseClicked
        if (IdSearch.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "id cant be empty");
        } else {
            search();
        }
    }//GEN-LAST:event_search_textMouseClicked

    private void search_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_ButtonMouseClicked
        if (IdSearch.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "id cant be empty");
        } else {
            search();
        }
    }//GEN-LAST:event_search_ButtonMouseClicked

    private void back_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_buttonMouseClicked

    }//GEN-LAST:event_back_buttonMouseClicked

    private void Id_ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_ModifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_ModifyActionPerformed

    private void phone_Modify1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_Modify1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_Modify1ActionPerformed

    private void usr_Modify2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usr_Modify2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usr_Modify2ActionPerformed

    private void year_Modify4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year_Modify4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year_Modify4ActionPerformed

    private void gender_Modify5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender_Modify5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gender_Modify5ActionPerformed

    private void add_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_textMouseClicked
        creat();
    }//GEN-LAST:event_add_textMouseClicked

    private void add_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseClicked
        creat();

    }//GEN-LAST:event_add_buttonMouseClicked

    private void deleteBook_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBook_buttonMouseClicked
        delete();
    }//GEN-LAST:event_deleteBook_buttonMouseClicked

    private void deleteBook_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBook_textMouseClicked
        delete();
    }//GEN-LAST:event_deleteBook_textMouseClicked

    private void Update_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_textMouseClicked
        update();
    }//GEN-LAST:event_Update_textMouseClicked

    private void update_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_buttonMouseClicked
        update();
    }//GEN-LAST:event_update_buttonMouseClicked

    private void signed_Modify6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signed_Modify6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signed_Modify6ActionPerformed

    private void rSTableMetro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSTableMetro1MouseClicked

        int row = rSTableMetro1.getSelectedRow();
        TableModel getModel = rSTableMetro1.getModel();

        if (row >= 0) {
            Id_Modify.setText(getModel.getValueAt(row, 0).toString());
            name_Modify.setText(getModel.getValueAt(row, 1).toString());
            gender_Modify5.setText(getModel.getValueAt(row, 2).toString());
            year_Modify4.setText(getModel.getValueAt(row, 3).toString());
            address_Modify.setText(getModel.getValueAt(row, 4).toString());
            phone_Modify1.setText(getModel.getValueAt(row, 5).toString());
            usr_Modify2.setText(getModel.getValueAt(row, 6).toString());
            signed_Modify6.setText(getModel.getValueAt(row, 7).toString());
        }
    }//GEN-LAST:event_rSTableMetro1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ManageEmployee().setVisible(true);
//            }
//        });
    }

    public void delete() {
        try {
            int id = Integer.parseInt(Id_Modify.getText());

            if (employeeDAO.delete(id)) {

                deleteRow();
                setTable();
                JOptionPane.showMessageDialog(this, "delte successful");
            } else {
                JOptionPane.showMessageDialog(this, "delte unsuccessful");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "invalid text");
            e.printStackTrace();
        }
    }

    public void update() {
        try {
            Employee employee = new Employee();
            employee.setId(Integer.valueOf(Id_Modify.getText()));
            employee.setFullname(name_Modify.getText());
            employee.setGender(gender_Modify5.getText());
            employee.setYear(Integer.valueOf(year_Modify4.getText()));
            employee.setAddress(address_Modify.getText());
            employee.setPhone(phone_Modify1.getText());
            employee.setUsername(usr_Modify2.getText());
            employee.setSignedin(Integer.parseInt(signed_Modify6.getText()));

            if (employeeDAO.update(employee)) {

                deleteRow();
                setTable();
                JOptionPane.showMessageDialog(this, "update successful");
            } else {
                JOptionPane.showMessageDialog(this, "update unsuccessful may be your username is duplicated");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "invalid text");
            e.printStackTrace();
        }
    }

    public void creat() {
        try {
            Employee employee = new Employee();
            employee.setFullname(name_Modify.getText());
            employee.setGender(gender_Modify5.getText());
            employee.setYear(Integer.valueOf(year_Modify4.getText()));
            employee.setAddress(address_Modify.getText());
            employee.setPhone(phone_Modify1.getText());
            employee.setUsername(usr_Modify2.getText());
            employee.setSignedin(Integer.parseInt(signed_Modify6.getText()));

            if (employeeDAO.checkDuplicate(employee.getUsername())) {
                int n = employeeDAO.creat(employee);
                if (n > 0) {
                    Id_Modify.setText(Integer.toString(n));
                    deleteRow();
                    setTable();
                    JOptionPane.showMessageDialog(this, "creat successful");
                } else {
                    JOptionPane.showMessageDialog(this, "creat unsuccessful");
                }
            } else {
                JOptionPane.showMessageDialog(this, "your username is duplicate");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "invalid text");
            e.printStackTrace();
        }

    }

    public void search() {
        try {
            Employee employee = employeeDAO.search(Integer.parseInt(IdSearch.getText()));

            if (employee != null) {
                Id_Modify.setText(Integer.toString(employee.getId()));
                name_Modify.setText(employee.getFullname());
                address_Modify.setText(employee.getAddress());
                gender_Modify5.setText(employee.getGender());
                phone_Modify1.setText(employee.getPhone());
                year_Modify4.setText(Integer.toString(employee.getYear()));
                signed_Modify6.setText(Integer.toString(employee.getSignedin()));
                usr_Modify2.setText(employee.getUsername());

                deleteRow();
                Object[] obj = {employee.getId(), employee.getFullname(), employee.getGender(), employee.getYear(), employee.getAddress(), employee.getPhone(), employee.getUsername(), employee.getSignedin()};

                model.addRow(obj);
            } else if (!name_search.getText().equals("")) {

                ResultSet rs = employeeDAO.searchByName(name_search.getText());
                if (rs != null) {
                    deleteRow();
                    while (rs.next()) {
                        int id = rs.getInt(1);
                        String name = rs.getString(2);
                        String gender = rs.getString(3);
                        int year = rs.getInt(4);
                        String address = rs.getString(5);
                        String phone = rs.getString(6);
                        String username = rs.getString(7);
                        int signedin = rs.getInt(8);

                        Object[] obj = {id, name, gender, year, address, phone, username, signedin};
                        model = (DefaultTableModel) rSTableMetro1.getModel();
                        model.addRow(obj);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "cant find this ");
                }

            } else {
                JOptionPane.showMessageDialog(this, "cant find this ");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "invalid text");
            e.printStackTrace();
        }
    }

    public void deleteRow() {
        int n = model.getRowCount();
        for (int i = n - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }

    public void setTable() {
        ResultSet rs = employeeDAO.searchAll();

        try {
            if (rs != null) {
                while (rs.next()) {
                    Object[] obj = {rs.getInt("EMP_ID"), rs.getString("Fullname"), rs.getString("Gender"), rs.getInt("YearOfBirth"), rs.getString("EmAddress"), rs.getString("Phone"), rs.getString("usrname"), rs.getInt("signedin")};
                    model = (DefaultTableModel) rSTableMetro1.getModel();
                    model.addRow(obj);
                }
            }
        } catch (Exception e) {
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdSearch;
    private javax.swing.JTextField Id_Modify;
    private javax.swing.JLabel Num_emp;
    private javax.swing.JLabel Num_logout;
    private javax.swing.JLabel Num_singed;
    private javax.swing.JLabel Update_text;
    private keeptoo.KGradientPanel add_button;
    private javax.swing.JLabel add_text;
    private javax.swing.JTextField address_Modify;
    private javax.swing.JLabel back_button;
    private keeptoo.KGradientPanel deleteBook_button;
    private javax.swing.JLabel deleteBook_text;
    private javax.swing.JTextField gender_Modify5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private javax.swing.JTextField name_Modify;
    private javax.swing.JTextField name_search;
    private javax.swing.JTextField phone_Modify1;
    private rojerusan.RSTableMetro rSTableMetro1;
    private keeptoo.KGradientPanel search_Button;
    private javax.swing.JLabel search_text;
    private javax.swing.JTextField signed_Modify6;
    private keeptoo.KGradientPanel update_button;
    private javax.swing.JTextField usr_Modify2;
    private javax.swing.JTextField year_Modify4;
    // End of variables declaration//GEN-END:variables
}
